# Form implementation generated from reading ui file 'src/fleasion/gui/rules_dialog.ui'
#
# Created by: PySide6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.
from typing import TYPE_CHECKING

from PySide6 import QtCore, QtWidgets

from fleasion.localization import tr


def _header_item(table: QtWidgets.QTableWidget, index: int) -> QtWidgets.QTableWidgetItem:
    item = table.horizontalHeaderItem(index)
    if TYPE_CHECKING:
        assert item is not None
    return item


class UiDialog:
    def setup_ui(self, dialog: QtWidgets.QDialog) -> None:
        dialog.setObjectName('Dialog')
        dialog.resize(611, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName('verticalLayout')
        self.rulesTable = QtWidgets.QTableWidget(parent=dialog)
        self.rulesTable.setColumnCount(7)
        self.rulesTable.setObjectName('rulesTable')
        self.rulesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.rulesTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.addRuleButton = QtWidgets.QPushButton(parent=dialog)
        self.addRuleButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.addRuleButton.setObjectName('addRuleButton')
        self.horizontalLayout.addWidget(self.addRuleButton)
        self.duplicateRuleButton = QtWidgets.QPushButton(parent=dialog)
        self.duplicateRuleButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.duplicateRuleButton.setObjectName('duplicateRuleButton')
        self.horizontalLayout.addWidget(self.duplicateRuleButton)
        self.deleteRuleButton = QtWidgets.QPushButton(parent=dialog)
        self.deleteRuleButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.deleteRuleButton.setObjectName('deleteRuleButton')
        self.horizontalLayout.addWidget(self.deleteRuleButton)
        self.importButton = QtWidgets.QPushButton(parent=dialog)
        self.importButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.importButton.setObjectName('importButton')
        self.horizontalLayout.addWidget(self.importButton)
        self.exportButton = QtWidgets.QPushButton(parent=dialog)
        self.exportButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.exportButton.setObjectName('exportButton')
        self.horizontalLayout.addWidget(self.exportButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslate_ui(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslate_ui(self, dialog: QtWidgets.QDialog) -> None:
        dialog.setWindowTitle(tr('ui.gui.rules_dialog_ui.dialog'))
        item = _header_item(self.rulesTable, 0)
        item.setText(tr('ui.gui.rules_dialog_ui.enabled'))
        item = _header_item(self.rulesTable, 1)
        item.setText(tr('ui.gui.rules_dialog_ui.direction'))
        item = _header_item(self.rulesTable, 2)
        item.setText(tr('ui.gui.rules_dialog_ui.type'))
        item = _header_item(self.rulesTable, 3)
        item.setText(tr('ui.gui.rules_dialog_ui.match_path'))
        item = _header_item(self.rulesTable, 4)
        item.setText(tr('ui.gui.rules_dialog_ui.replacement'))
        item = _header_item(self.rulesTable, 5)
        item.setText(tr('ui.gui.rules_dialog_ui.host_filter'))
        item = _header_item(self.rulesTable, 6)
        item.setText(tr('ui.gui.rules_dialog_ui.path_filter'))
        self.addRuleButton.setText(tr('ui.gui.rules_dialog_ui.add'))
        self.duplicateRuleButton.setText(tr('ui.gui.rules_dialog_ui.duplicate'))
        self.deleteRuleButton.setText(tr('ui.gui.rules_dialog_ui.delete'))
        self.importButton.setText(tr('ui.gui.rules_dialog_ui.import'))
        self.exportButton.setText(tr('ui.gui.rules_dialog_ui.export'))
