from ..localization import tr
# Form implementation generated from reading ui file 'src/fleasion/gui/rules_dialog.ui'
#
# Created by: PySide6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName('Dialog')
        Dialog.resize(611, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName('verticalLayout')
        self.rulesTable = QtWidgets.QTableWidget(parent=Dialog)
        self.rulesTable.setColumnCount(7)
        self.rulesTable.setObjectName('rulesTable')
        self.rulesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.rulesTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.addRuleButton = QtWidgets.QPushButton(parent=Dialog)
        self.addRuleButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.addRuleButton.setObjectName('addRuleButton')
        self.horizontalLayout.addWidget(self.addRuleButton)
        self.duplicateRuleButton = QtWidgets.QPushButton(parent=Dialog)
        self.duplicateRuleButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.duplicateRuleButton.setObjectName('duplicateRuleButton')
        self.horizontalLayout.addWidget(self.duplicateRuleButton)
        self.deleteRuleButton = QtWidgets.QPushButton(parent=Dialog)
        self.deleteRuleButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.deleteRuleButton.setObjectName('deleteRuleButton')
        self.horizontalLayout.addWidget(self.deleteRuleButton)
        self.importButton = QtWidgets.QPushButton(parent=Dialog)
        self.importButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.importButton.setObjectName('importButton')
        self.horizontalLayout.addWidget(self.importButton)
        self.exportButton = QtWidgets.QPushButton(parent=Dialog)
        self.exportButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.exportButton.setObjectName('exportButton')
        self.horizontalLayout.addWidget(self.exportButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(tr('ui.gui.rules_dialog_ui.dialog'))
        item = self.rulesTable.horizontalHeaderItem(0)
        item.setText(tr('ui.gui.rules_dialog_ui.enabled'))
        item = self.rulesTable.horizontalHeaderItem(1)
        item.setText(tr('ui.gui.rules_dialog_ui.direction'))
        item = self.rulesTable.horizontalHeaderItem(2)
        item.setText(tr('ui.gui.rules_dialog_ui.type'))
        item = self.rulesTable.horizontalHeaderItem(3)
        item.setText(tr('ui.gui.rules_dialog_ui.match_path'))
        item = self.rulesTable.horizontalHeaderItem(4)
        item.setText(tr('ui.gui.rules_dialog_ui.replacement'))
        item = self.rulesTable.horizontalHeaderItem(5)
        item.setText(tr('ui.gui.rules_dialog_ui.host_filter'))
        item = self.rulesTable.horizontalHeaderItem(6)
        item.setText(tr('ui.gui.rules_dialog_ui.path_filter'))
        self.addRuleButton.setText(tr('ui.gui.rules_dialog_ui.add'))
        self.duplicateRuleButton.setText(tr('ui.gui.rules_dialog_ui.duplicate'))
        self.deleteRuleButton.setText(tr('ui.gui.rules_dialog_ui.delete'))
        self.importButton.setText(tr('ui.gui.rules_dialog_ui.import'))
        self.exportButton.setText(tr('ui.gui.rules_dialog_ui.export'))
