class vtkMatrix4x4:
    def Identity(self) -> None: ...
    def SetElement(self, row: int, column: int, value: float) -> None: ...
    def GetElement(self, row: int, column: int) -> float: ...
    @staticmethod
    def Multiply4x4(a: vtkMatrix4x4, b: vtkMatrix4x4, out: vtkMatrix4x4) -> None: ...
    @staticmethod
    def Invert(a: vtkMatrix4x4, out: vtkMatrix4x4) -> None: ...

class vtkLight:
    def SetLightTypeToHeadlight(self) -> None: ...
    def SetLightTypeToSceneLight(self) -> None: ...
    def SetPosition(self, x: float, y: float, z: float) -> None: ...
    def SetFocalPoint(self, x: float, y: float, z: float) -> None: ...
    def SetIntensity(self, intensity: float) -> None: ...

class vtkActor:
    def SetUserMatrix(self, matrix: vtkMatrix4x4) -> None: ...

class vtkRenderer:
    def RemoveAllLights(self) -> None: ...
    def AddLight(self, light: vtkLight) -> None: ...

class vtkCamera:
    focal_point: tuple[float, float, float]
    position: tuple[float, float, float]
    up: tuple[float, float, float]
    view_angle: float
    def SetClippingRange(self, near: float, far: float) -> None: ...
    def Azimuth(self, angle: float) -> None: ...
