"""Utilities package."""

from .logging import LogBuffer, log_buffer
from .plural import format_count, pluralize
from .time_tracker import TimeTracker, time_tracker
from .paths import (
    APP_AUTHOR,
    APP_LOGIC,
    APP_CONCEPT,
    APP_DISCORD,
    APP_REPO,
    APP_NAME,
    APP_VERSION,
    APP_CACHE_DIR,
    CLOG_URL,
    CONFIG_DIR,
    CONFIG_FILE,
    CONFIGS_FOLDER,
    DEFAULT_SETTINGS,
    ICON_FILENAME,
    LOCAL_APPDATA,
    LOG_FILE,
    LOGS_DIR,
    MACOS_PROXY_BACKEND_PORT,
    MACOS_PROXY_HELPER_CONTROL_PORT,
    MOD_CACHE_DIR,
    MOD_ORIGINALS_DIR,
    MODIFICATIONS_JSON,
    ORIGINALS_DIR,
    PREJSONS_DIR,
    PROXY_CA_DIR,
    PROXY_PORT,
    PROXY_TARGET_HOST,
    REPLACEMENTS_DIR,
    ROBLOX_PROCESS,
    ROBLOX_STUDIO_PROCESS,
    STORAGE_DB,
    STORAGE_DB_GDK,
    STRIPPABLE_ASSET_TYPES,
    USER_HOME,
    get_icon_path,
)
from .threading import run_in_thread
from .windows import (
    delete_cache,
    get_roblox_player_exe_path,
    get_roblox_studio_exe_path,
    is_roblox_running,
    is_studio_running,
    open_folder,
    show_message_box,
    terminate_roblox,
    wait_for_roblox_exit,
    wait_for_roblox_window,
)


def start_update_check(*args, **kwargs):
    from .updater import start_update_check as _start_update_check

    return _start_update_check(*args, **kwargs)

__all__ = [
    'APP_AUTHOR',
    'APP_LOGIC',
    'APP_CONCEPT',
    'APP_DISCORD',
    'APP_REPO',
    'APP_NAME',
    'APP_VERSION',
    'APP_CACHE_DIR',
    'CLOG_URL',
    'CONFIG_DIR',
    'CONFIG_FILE',
    'CONFIGS_FOLDER',
    'DEFAULT_SETTINGS',
    'ICON_FILENAME',
    'LOCAL_APPDATA',
    'LOG_FILE',
    'LOGS_DIR',
    'MACOS_PROXY_BACKEND_PORT',
    'MACOS_PROXY_HELPER_CONTROL_PORT',
    'MOD_CACHE_DIR',
    'MOD_ORIGINALS_DIR',
    'MODIFICATIONS_JSON',
    'ORIGINALS_DIR',
    'PREJSONS_DIR',
    'PROXY_CA_DIR',
    'PROXY_PORT',
    'PROXY_TARGET_HOST',
    'REPLACEMENTS_DIR',
    'ROBLOX_PROCESS',
    'ROBLOX_STUDIO_PROCESS',
    'STORAGE_DB',
    'STORAGE_DB_GDK',
    'STRIPPABLE_ASSET_TYPES',
    'USER_HOME',
    'LogBuffer',
    'TimeTracker',
    'time_tracker',
    'delete_cache',
    'get_icon_path',
    'format_count',
    'get_roblox_player_exe_path',
    'get_roblox_studio_exe_path',
    'is_roblox_running',
    'is_studio_running',
    'log_buffer',
    'open_folder',
    'pluralize',
    'run_in_thread',
    'start_update_check',
    'show_message_box',
    'terminate_roblox',
    'wait_for_roblox_exit',
    'wait_for_roblox_window',
]
